# ==============================================================================
# docker-compose
# ==============================================================================
version: '3'
services:
  # ----------------------------------------------------------------------------
  app: &app-base
  # ----------------------------------------------------------------------------
    build:
      context: .
      dockerfile: docker/local.Dockerfile
      args:
        RAILS_ENV: development
    command: bundle exec rails server -b 0.0.0.0 -p '3000'
    ports:
      - '3000:3000'
    links:
      - postgres
      - redis
    environment:
      LANG: 'C.UTF-8'
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      RAILS_ENV: development
      REDIS_URL: redis://redis:6379/0
      SPRING_SOCKET: 'tmp/pids/spring.sock'
      SPRING_SERVER_COMMAND: 'docker-compose up spring'
    env_file:
      - secrets.env
    volumes:
      - nfs_app:/rails_app
      - bundle-data:/usr/local/bundle
    stdin_open: true
    tty: true


  # ----------------------------------------------------------------------------
  worker:
  # ----------------------------------------------------------------------------
    <<: *app-base
    build:
      context: .
      dockerfile: docker/local.Dockerfile
      args:
        RAILS_ENV: development
    ports: []
    command: bundle exec sidekiq -C config/sidekiq.yml


  # ----------------------------------------------------------------------------
  spring:
  # ----------------------------------------------------------------------------
    <<: *app-base
    ports: []
    command: bundle exec spring server
    pid: host


  # ----------------------------------------------------------------------------
  postgres:
  # ----------------------------------------------------------------------------
    image: postgres:12.2-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres-data:/var/lib/postgresql/data


  # ----------------------------------------------------------------------------
  redis:
  # ----------------------------------------------------------------------------
    image: redis:5.0.7-alpine
    ports:
      - '6379:6379'
    command: [redis-server, --loglevel, notice]
    volumes:
      - redis-data:/data


  # ----------------------------------------------------------------------------
  mailcatcher:
  # ----------------------------------------------------------------------------
    image: schickling/mailcatcher
    ports:
      - '1080:1080'


# ----------------------------------------------------------------------------
volumes:
# ----------------------------------------------------------------------------
  bundle-data: {}
  postgres-data: {}
  redis-data: {}
  dynamodb-data: {}
  nfs_app:
    driver: 'local'
    driver_opts:
      type: 'nfs'
      o: 'addr=host.docker.internal,rw,nolock,hard,nointr,actimeo=1,nfsvers=3'
      device: ':${PWD}'
